"""
Manual, one-off check against a REAL LLM provider. Not part of the
automated suite - pytest won't collect this (doesn't match test_*.py),
and deliberately so: this costs a small amount of money (or, on Ollama,
real wall-clock time) and needs network + a real key, neither of which
belongs in a suite that should run free and offline on every commit.

Requires LLM_API_KEY (and, for Ollama, LLM_API_BASE) in .env set for
whatever LLM_PROVIDER / LLM_MODEL are configured to.

Two real LLM calls happen now (Scenario Agent, then TestCase Agent) - on
local Ollama this can easily take 2-4 minutes total. That's expected,
not a hang.

Run with:
    python -m backend.live_check
"""

from backend.graph.workflow import run_workflow
from backend.models.requirement import Requirement
from backend.services.llm import LLMServiceError

# Deliberately NOT login-related. The old dummy data used "Valid Login" /
# "Invalid Login" / "Empty Password" - if this requirement were about
# login too, a real LLM producing similar-sounding names wouldn't prove
# anything. A clearly different domain makes it obvious the scenarios
# below are genuinely generated, not leftover dummy data.
_REQUIREMENT = Requirement(
    title="Profile picture upload size limit",
    description=(
        "Users can upload a profile picture up to 5MB in size, in JPG or "
        "PNG format only. Uploads exceeding the limit or in an unsupported "
        "format must be rejected with a clear error message, and the "
        "previous picture must remain unchanged if the upload fails."
    ),
)


def main():
    print(f"Sending requirement to the real LLM: '{_REQUIREMENT.title}'\n")

    try:
        final_state = run_workflow(_REQUIREMENT)
    except LLMServiceError as exc:
        print("Live call failed. Usual causes, in order of likelihood:")
        print("  1. LLM_API_KEY in .env is missing, empty, or invalid")
        print("  2. The account behind that key has no billing/quota set up")
        print("  3. LLM_PROVIDER / LLM_MODEL in .env don't match a real, available model")
        print(f"\nUnderlying error: {exc}")
        return

    print("Log trail:")
    for line in final_state.logs:
        print("   ", line)

    print("\nScenarios generated by the LLM:")
    for s in final_state.generated_scenarios:
        print(f"    - {s.scenario_name} [{s.priority.value}]: {s.description}")

    print("\nTest cases generated:")
    for tc in final_state.generated_test_cases:
        print(f"    - {tc.title} [{tc.priority.value}]")
        print(f"        preconditions: {tc.preconditions}")
        print(f"        steps: {tc.steps}")
        print(f"        expected: {tc.expected_result}")

    print(
        "\nIf the scenarios above are specifically about file size, format "
        "validation, and rejection (not generic login scenarios), the live "
        "LLM integration is genuinely working end to end - not just passing "
        "mocked tests."
    )


if __name__ == "__main__":
    main()