import os
import logging
from datetime import datetime, timezone
from pydantic import BaseModel, Field
from backend.agents.base import BaseAgent
from backend.models.state import WorkflowState
from backend.models.execution_result import ExecutionStatus
from backend.services.llm import LLMService
from backend.services.jira_service import JiraService
from backend.utils.prompts import load_prompt

logger = logging.getLogger("backend.agents.defect_management_agent")


class _DefectSearchResponse(BaseModel):
    jira_search_query: str = Field(description="JQL search term to look up duplicate bugs")
    is_duplicate_candidate: bool = Field(description="True if we suspect a duplicate bug exists")
    bug_title: str = Field(description="Proposed title for the JIRA Bug if not a duplicate")
    bug_description: str = Field(description="Proposed description for the JIRA Bug if not a duplicate")


class DefectManagementAgent(BaseAgent):
    name = "Defect Management Agent"

    def __init__(self, llm_service: LLMService | None = None, jira_service: JiraService | None = None):
        self.llm_service = llm_service or LLMService()
        self.jira_service = jira_service or JiraService()

    def run(self, state: WorkflowState) -> WorkflowState:
        if not state.execution_results:
            state.add_log(f"{self.name}: no execution results found.")
            return state

        result = state.execution_results[-1]
        
        # We only file bugs for verified Product Bugs
        if result.status == ExecutionStatus.PASSED or result.failure_category != "Product Bug":
            state.add_log(f"{self.name}: skip bug sync as status is {result.status.value} / category is {result.failure_category}")
            return state

        state.add_log(f"{self.name} started processing defect for execution {result.id}")

        # Find the test case in state
        tc = next((t for t in state.generated_test_cases if t.id == result.test_case_id), None)
        tc_title = tc.title if tc else "Unknown Test Case"
        tc_steps = "\n".join(f"- {s}" for s in tc.steps) if tc else "N/A"

        prompt = load_prompt(
            "defect_agent_prompt.txt",
            title=tc_title,
            steps=tc_steps,
            failure_message=result.error_message or "Unknown failure",
            trace_log=result.error_message or "Unknown failure"
        )

        try:
            analysis = self.llm_service.structured_generate(
                user=prompt,
                response_model=_DefectSearchResponse
            )

            # Query Jira for duplicates using the JQL generated by LLM
            existing = self.jira_service.search_issues(analysis.jira_search_query)
            if existing:
                issue = existing[0]
                key = issue["key"]
                state.add_log(f"{self.name}: duplicate defect detected: {key}")
                
                # Link execution via comment
                comment = (
                    f"Test execution failed again at {result.executed_at.isoformat()}.\n"
                    f"Error Message: {result.error_message or 'No specific error log provided.'}"
                )
                self.jira_service.add_comment(key, comment)
                
                result.jira_bug_id = key
                result.jira_bug_url = f"{self.jira_service.config.base_url.rstrip('/')}/browse/{key}"
                
                if tc:
                    tc.jira_issue_key = key
                    tc.jira_issue_url = result.jira_bug_url
                    tc.jira_sync_status = "linked"
                    tc.jira_last_synced_at = datetime.now(timezone.utc)
            else:
                # Create a new Bug in Jira
                labels = ["platform_sync", f"test_{tc.id if tc else 'unknown'}", "bug"]
                issue = self.jira_service.create_issue(
                    summary=analysis.bug_title,
                    description=analysis.bug_description,
                    issue_type="Bug",
                    labels=labels
                )
                
                if issue:
                    key = issue["key"]
                    result.jira_bug_id = key
                    result.jira_bug_url = issue["url"]
                    
                    if tc:
                        tc.jira_issue_key = key
                        tc.jira_issue_url = issue["url"]
                        tc.jira_sync_status = "created"
                        tc.jira_last_synced_at = datetime.now(timezone.utc)
                    
                    # Attach runner screenshot if captured
                    if result.screenshot_path and os.path.exists(result.screenshot_path):
                        try:
                            with open(result.screenshot_path, "rb") as f:
                                self.jira_service.upload_attachment(key, "screenshot.png", f.read(), "image/png")
                        except Exception as attach_err:
                            logger.error(f"Failed to upload attachment: {attach_err}")
                            
                    state.add_log(f"{self.name}: created JIRA Bug: {key}")

        except Exception as exc:
            state.add_log(f"{self.name} failed: {exc}")

        return state
