"""
ScenarioAgent

Purpose:
    Generates test scenarios from requirements using LLM structured output.
    Expands requirement descriptions into concrete test scenarios covering happy paths,
    edge cases, and negative flows.

Responsibilities:
    - Load scenario generation prompt template
    - Invoke LLM with structured response schema (_GeneratedScenarioBatch)
    - Validate LLM output against Pydantic schema
    - Convert LLM content into Scenario domain objects
    - Populate system-owned fields (id, requirement_id, generated_at)
    - Append generated scenarios to workflow state

Workflow Position:
    RequirementAnalystAgent (optional, for INGEST flow)
        ↓
    QAStoryAnalyzerAgent (optional, for BACKLOG flow)
        ↓
    ScenarioAgent
        ↓
    HumanApprovalAgent
        ↓
    TestCaseAgent

Inputs:
    - state.requirement: Requirement object with title and description
    - settings.generation.scenario_count: Number of scenarios to generate

Outputs:
    - state.generated_scenarios: List of Scenario objects

LLM Contract:
    - Input: Requirement title, description, count
    - Output: _GeneratedScenarioBatch with scenarios array
    - Fields: scenario_name, description, priority, confidence, path_type, tags
    - System-owned fields (id, requirement_id, approved, generated_at) are NOT generated by LLM

Design Decision:
    The LLM generates content only (names, descriptions, priorities).
    System-owned metadata is assigned by the agent, not the model.
    This prevents the LLM from inventing IDs or approval statuses.
"""

from pydantic import BaseModel, Field, field_validator

from backend.agents.base import BaseAgent
from backend.config.settings import get_settings
from backend.models.common import Priority
from backend.models.scenario import Scenario
from backend.models.state import WorkflowState
from backend.services.llm import LLMService
from backend.utils.prompts import load_prompt


# ==========================================================
# LLM Output Schema (Content Contract)
# ==========================================================

class _GeneratedScenario(BaseModel):
    """
    Single scenario generated by LLM.
    
    Contains ONLY content fields - no system metadata.
    Agent is responsible for wrapping this into Scenario domain object.
    """
    scenario_name: str = Field(min_length=1, max_length=200)
    description: str = Field(min_length=1)
    priority: Priority = Priority.MEDIUM
    confidence: float = Field(ge=0.0, le=1.0, default=0.95)
    path_type: str = Field(description="Type of test path: 'happy_path', 'negative', or 'edge_case'")
    tags: list[str] = Field(default_factory=list)

    @field_validator("priority", mode="before")
    @classmethod
    def _normalize_case(cls, value):
        """
        Normalize priority to a known enum value.
        LLMs use "high"/"High"/"HIGH" or "critical"/"Critical"/"CRITICAL".
        Map "critical" to "high" since there's no Critical enum value.
        """
        if isinstance(value, str):
            v = value.lower().strip()
            if v in ("critical", "crit", "critical high", "highest"):
                return "high"
            if v in ("lowest", "lowest priority"):
                return "low"
            return v
        return value


class _GeneratedScenarioBatch(BaseModel):
    """Batch of scenarios returned by LLM in a single call."""
    scenarios: list[_GeneratedScenario] = Field(min_length=1)


# ==========================================================
# Scenario Generation Agent
# ==========================================================

class ScenarioAgent(BaseAgent):
    """
    LLM-powered scenario generation agent.
    
    Converts requirement descriptions into concrete test scenarios
    using structured LLM output.
    """
    
    name = "Scenario Agent"

    def __init__(self, llm_service: LLMService | None = None, scenario_count: int | None = None):
        """
        Initialize scenario agent with LLM service and generation count.
        
        Args:
            llm_service: LLM service instance (injected for testing)
            scenario_count: Number of scenarios to generate (defaults to settings.generation.scenario_count)
        """
        self.llm_service = llm_service or LLMService()
        self.scenario_count = scenario_count or get_settings().generation.scenario_count

    def run(self, state: WorkflowState) -> WorkflowState:
        """
        Generate test scenarios from requirement using LLM.
        
        Args:
            state: Workflow state containing requirement
            
        Returns:
            Updated state with generated_scenarios populated
            
        Raises:
            ValueError: If state.requirement is None
            LLMServiceError: If LLM output does not match schema
            
        Process:
            1. Validate requirement exists in state
            2. Load prompt template with requirement details
            3. Call LLM with structured output schema
            4. Validate LLM output against _GeneratedScenarioBatch
            5. Convert _GeneratedScenario to Scenario domain objects
            6. Append to state.generated_scenarios
        """
        if state.requirement is None:
            raise ValueError(f"{self.name} requires state.requirement to be set")

        state.add_log(f"{self.name} started")

        prompt = load_prompt(
            "scenario_prompt.txt",
            title=state.requirement.title,
            description=state.requirement.description,
            count=str(self.scenario_count),
        )

        batch = self.llm_service.structured_generate(
            user=prompt,
            response_model=_GeneratedScenarioBatch,
        )

        for item in batch.scenarios:
            state.generated_scenarios.append(
                Scenario(
                    requirement_id=state.requirement.id,
                    scenario_name=item.scenario_name,
                    description=item.description,
                    priority=item.priority,
                    confidence=item.confidence,
                    path_type=item.path_type,
                    tags=item.tags,
                )
            )

        state.add_log(f"{self.name} generated {len(batch.scenarios)} scenarios")
        return state