"""
TestCaseAgent

Purpose:
    Generates executable test cases from approved scenarios using LLM structured output.
    Expands high-level scenario descriptions into detailed test steps with preconditions,
    actions, and expected results.

Responsibilities:
    - Load test case generation prompt template
    - Format scenarios as numbered list for LLM correlation
    - Invoke LLM with structured response schema (TestCaseListResponse)
    - Validate scenario_number correlation (must match 1..N exactly)
    - Convert LLM content into TestCase domain objects
    - Inherit priority from parent scenario
    - Append generated test cases to workflow state

Workflow Position:
    ScenarioAgent
        ↓
    HumanApprovalAgent (scenario approval)
        ↓
    TestCaseAgent
        ↓
    EvaluationAgent
        ↓
    HumanApprovalAgent (test case approval)
        ↓
    PlaywrightAgent

Inputs:
    - state.requirement: Requirement context
    - state.generated_scenarios: List of approved scenarios

Outputs:
    - state.generated_test_cases: List of TestCase objects

LLM Correlation:
    Uses scenario_number (1-based index) instead of scenario_name to avoid
    paraphrasing issues. LLM must return exactly {1, 2, ..., N} scenario numbers.
    
    Historical Issue:
        Previously used scenario_name echo-back for correlation.
        Failed in production when LLM returned "Upload exceeds Limit" for
        scenario named "Upload exceeds Limit (5.1MB PNG)".
        Numbers don't get paraphrased - switched to index-based correlation.

Design Decision:
    Priority is inherited from parent scenario, not generated by LLM.
    This prevents disagreement between scenario and test case priorities.
    LLM generates only content: title, preconditions, steps, expected_result, test_data.
"""

from pydantic import BaseModel, Field

from backend.agents.base import BaseAgent
from backend.models.scenario import Scenario
from backend.models.state import WorkflowState
from backend.models.test_case import TestCase
from backend.services.llm import LLMService, LLMServiceError
from backend.utils.prompts import load_prompt


# ==========================================================
# LLM Output Schema
# ==========================================================

class TestCaseResponse(BaseModel):
    """
    Single test case generated by LLM.
    
    scenario_number is 1-based index into the scenarios list provided in prompt.
    """
    scenario_number: int = Field(ge=1)
    title: str = Field(min_length=1, max_length=200)
    preconditions: list[str] = Field(default_factory=list)
    steps: list[str] = Field(min_length=1)
    expected_result: str = Field(min_length=1)
    test_data: dict[str, str] = Field(default_factory=dict)


class TestCaseListResponse(BaseModel):
    """Batch of test cases returned by LLM."""
    test_cases: list[TestCaseResponse] = Field(min_length=1)


# ==========================================================
# Helper Functions
# ==========================================================

def _format_scenarios_block(scenarios: list[Scenario]) -> str:
    """
    Format scenarios as numbered list for LLM prompt.
    
    Args:
        scenarios: List of Scenario objects
        
    Returns:
        Formatted string with numbered scenarios including priority
        
    Example:
        1. Login with valid credentials (priority: high): User can authenticate...
        2. Login with invalid password (priority: medium): System rejects...
    """
    return "\n".join(
        f"{i + 1}. {s.scenario_name} (priority: {s.priority.value}): {s.description}"
        for i, s in enumerate(scenarios)
    )


# ==========================================================
# Test Case Generation Agent
# ==========================================================

class TestCaseAgent(BaseAgent):
    """
    LLM-powered test case generation agent.
    
    Converts scenario descriptions into detailed, executable test cases.
    """
    
    name = "TestCase Agent"

    def __init__(self, llm_service: LLMService | None = None):
        """
        Initialize test case agent with LLM service.
        
        Args:
            llm_service: LLM service instance (injected for testing)
        """
        self.llm_service = llm_service or LLMService()

    def run(self, state: WorkflowState) -> WorkflowState:
        """
        Generate test cases from scenarios using LLM.
        
        Args:
            state: Workflow state containing requirement and scenarios
            
        Returns:
            Updated state with generated_test_cases populated
            
        Raises:
            ValueError: If state.requirement is None or no scenarios exist
            LLMServiceError: If LLM returns invalid scenario_number correlation
            
        Process:
            1. Validate requirement and scenarios exist
            2. Format scenarios as numbered list
            3. Call LLM with structured output schema
            4. Validate scenario_number correlation (must be exactly {1..N})
            5. Map test cases to parent scenarios via index
            6. Inherit priority from parent scenario
            7. Append to state.generated_test_cases
            
        Correlation Validation:
            LLM must return test cases for scenario numbers {1, 2, ..., N}.
            Missing or extra scenario numbers cause LLMServiceError.
        """
        if state.requirement is None:
            raise ValueError(f"{self.name} requires state.requirement to be set")
        if not state.generated_scenarios:
            raise ValueError(f"{self.name} requires at least one generated scenario")

        state.add_log(f"{self.name} started")

        prompt = load_prompt(
            "test_case_prompt.txt",
            title=state.requirement.title,
            description=state.requirement.description,
            scenarios=_format_scenarios_block(state.generated_scenarios),
            count=str(len(state.generated_scenarios)),
        )

        batch = self.llm_service.structured_generate(
            user=prompt,
            response_model=TestCaseListResponse,
        )

        expected_numbers = set(range(1, len(state.generated_scenarios) + 1))
        returned_numbers = {item.scenario_number for item in batch.test_cases}
        if returned_numbers != expected_numbers:
            raise LLMServiceError(
                f"{self.name}: LLM returned test cases for scenario numbers {sorted(returned_numbers)}, "
                f"expected exactly {sorted(expected_numbers)}"
            )

        for item in batch.test_cases:
            scenario = state.generated_scenarios[item.scenario_number - 1]
            state.generated_test_cases.append(
                TestCase(
                    scenario_id=scenario.id,
                    title=item.title,
                    preconditions=item.preconditions,
                    steps=item.steps,
                    expected_result=item.expected_result,
                    priority=scenario.priority,
                    test_data=item.test_data,
                )
            )

        state.add_log(f"{self.name} generated {len(state.generated_test_cases)} test cases")
        return state