"""add_rbac_and_audit

Revision ID: 1a821cd835fd
Revises: 14cf5447c245
Create Date: 2026-07-14 12:26:54.619121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a821cd835fd'
down_revision: Union[str, Sequence[str], None] = '14cf5447c245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('field_changes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_module'), 'audit_logs', ['module'], unique=False)
    op.create_index(op.f('ix_audit_logs_project_id'), 'audit_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('project_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_users_project_id'), 'project_users', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_users_role_id'), 'project_users', ['role_id'], unique=False)
    op.create_index(op.f('ix_project_users_user_id'), 'project_users', ['user_id'], unique=False)
    op.alter_column('documents', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('documents', 'project_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('executions', sa.Column('browser_version', sa.String(length=100), nullable=True))
    op.alter_column('executions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('executions', 'test_case_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('executions', 'project_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('projects', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('framework', sa.String(length=100), nullable=False))
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.alter_column('projects', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('projects', 'owner_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('reports', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('reports', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reports', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.alter_column('reports', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('reports', 'project_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('reports', 'execution_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_index(op.f('ix_reports_is_deleted'), 'reports', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'reports', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.add_column('requirements', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('requirements', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.alter_column('requirements', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('requirements', 'project_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_index(op.f('ix_requirements_is_deleted'), 'requirements', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'requirements', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.alter_column('scenario_notes', 'scenario_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('scenarios', sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('scenarios', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('scenarios', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.alter_column('scenarios', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('scenarios', 'requirement_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_index(op.f('ix_scenarios_is_deleted'), 'scenarios', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'scenarios', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.alter_column('test_case_notes', 'test_case_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('test_cases', sa.Column('is_frozen', sa.Boolean(), nullable=False))
    op.add_column('test_cases', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('test_cases', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.alter_column('test_cases', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('test_cases', 'scenario_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_index(op.f('ix_test_cases_is_deleted'), 'test_cases', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'test_cases', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'test_cases', type_='foreignkey')
    op.drop_index(op.f('ix_test_cases_is_deleted'), table_name='test_cases')
    op.alter_column('test_cases', 'scenario_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('test_cases', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('test_cases', 'deleted_by')
    op.drop_column('test_cases', 'is_deleted')
    op.drop_column('test_cases', 'is_frozen')
    op.alter_column('test_case_notes', 'test_case_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_constraint(None, 'scenarios', type_='foreignkey')
    op.drop_index(op.f('ix_scenarios_is_deleted'), table_name='scenarios')
    op.alter_column('scenarios', 'requirement_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('scenarios', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('scenarios', 'deleted_by')
    op.drop_column('scenarios', 'is_deleted')
    op.drop_column('scenarios', 'generated_at')
    op.alter_column('scenario_notes', 'scenario_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_constraint(None, 'requirements', type_='foreignkey')
    op.drop_index(op.f('ix_requirements_is_deleted'), table_name='requirements')
    op.alter_column('requirements', 'project_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('requirements', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('requirements', 'deleted_by')
    op.drop_column('requirements', 'is_deleted')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_is_deleted'), table_name='reports')
    op.alter_column('reports', 'execution_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reports', 'project_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reports', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('reports', 'deleted_by')
    op.drop_column('reports', 'deleted_at')
    op.drop_column('reports', 'is_deleted')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.alter_column('projects', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('projects', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('projects', 'deleted_by')
    op.drop_column('projects', 'is_deleted')
    op.drop_column('projects', 'framework')
    op.drop_column('projects', 'created_by')
    op.alter_column('executions', 'project_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('executions', 'test_case_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('executions', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('executions', 'browser_version')
    op.alter_column('documents', 'project_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_project_users_user_id'), table_name='project_users')
    op.drop_index(op.f('ix_project_users_role_id'), table_name='project_users')
    op.drop_index(op.f('ix_project_users_project_id'), table_name='project_users')
    op.drop_table('project_users')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_project_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_module'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
