"""add_jira_sync_metadata

Revision ID: 33e7bfda0aab
Revises: 475aa45cde0c
Create Date: 2026-07-18 14:32:07.787363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e7bfda0aab'
down_revision: Union[str, Sequence[str], None] = '475aa45cde0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('jira_attachment_id', sa.String(length=100), nullable=True))
    op.add_column('reports', sa.Column('jira_last_uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scenarios', sa.Column('jira_issue_id', sa.String(length=100), nullable=True))
    op.add_column('scenarios', sa.Column('last_jira_sync_error', sa.Text(), nullable=True))
    op.add_column('scenarios', sa.Column('jira_sync_retry_count', sa.Integer(), nullable=False, server_default="0"))
    op.create_index(op.f('ix_scenarios_rejected'), 'scenarios', ['rejected'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_rejected'), table_name='scenarios')
    op.drop_column('scenarios', 'jira_sync_retry_count')
    op.drop_column('scenarios', 'last_jira_sync_error')
    op.drop_column('scenarios', 'jira_issue_id')
    op.drop_column('reports', 'jira_last_uploaded_at')
    op.drop_column('reports', 'jira_attachment_id')
    # ### end Alembic commands ###
